import { router, json, secrets } from '@appdeploy/sdk';

const TRUCKDOWN_CONTEXT_URL='https://api.truckdown.com/client/accounts/get-context-information';
const TRUCKDOWN_OPENAPI_URL='https://api.truckdown.com/client/openapi.json';
const TRUCKDOWN_SEARCH_URL='https://api.truckdown.com/client/search';
const allowedServices=new Set(['mobile_repair','heavy_tow','tire_service','trailer_repair','diesel_repair']);
const serviceKeywords:Record<string,string[]>= {mobile_repair:['mobile','road','repair'],heavy_tow:['tow','towing','wrecker'],tire_service:['tire','tyre'],trailer_repair:['trailer'],diesel_repair:['diesel','engine','repair']};

type JsonObject=Record<string,unknown>;
type FieldSummary={name:string;required:boolean;type:string;enum?:unknown[];fields?:FieldSummary[];item_type?:string;item_fields?:FieldSummary[]};
type Candidate={candidate_id:string;source:'TRUCKDOWN';external_provider_ref:string|null;name:string;address:string|null;distance_miles:number|null;phone:string|null;rating:number|null;services:string[];observed_at:string};
let openApiCache:{expires:number;doc:JsonObject}|null=null;
function object(value:unknown):JsonObject{return value&&typeof value==='object'&&!Array.isArray(value)?value as JsonObject:{}}
function norm(value:string){return value.toLowerCase().replace(/[^a-z0-9]/g,'');}
function safeAccountType(value:unknown){const record=object(value);for(const key of ['accountType','account_type','plan','subscriptionType','subscription_type','type']){const candidate=record[key];if(typeof candidate==='string'&&candidate.length<=80)return candidate;}return 'unknown';}
function resolveRef(doc:JsonObject,value:unknown):JsonObject{let current=object(value);for(let i=0;i<8;i++){const ref=current['$ref'];if(typeof ref!=='string'||!ref.startsWith('#/'))break;let next:unknown=doc;for(const part of ref.slice(2).split('/'))next=object(next)[part.replace(/~1/g,'/').replace(/~0/g,'~')];current=object(next);}return current;}
function schemaType(doc:JsonObject,value:unknown){const schema=resolveRef(doc,value);const type=schema.type;if(typeof type==='string')return type;if(Array.isArray(type))return type.filter(v=>typeof v==='string').join('|')||'object';const ref=object(value)['$ref'];if(typeof ref==='string')return ref.split('/').pop()||'object';if(Object.keys(object(schema.properties)).length)return 'object';return 'object';}
function schemaFields(doc:JsonObject,value:unknown,depth=0):FieldSummary[]{const schema=resolveRef(doc,value);const required=new Set(Array.isArray(schema.required)?schema.required.filter(v=>typeof v==='string') as string[]:[]);const properties=object(schema.properties);return Object.entries(properties).slice(0,60).map(([name,definition])=>{const resolved=resolveRef(doc,definition);const type=schemaType(doc,definition);const field:FieldSummary={name,required:required.has(name),type};const enumValues=Array.isArray(resolved.enum)?resolved.enum.slice(0,30):[];if(enumValues.length)field.enum=enumValues;if(depth<1){if(type.includes('array')){const items=resolved.items;field.item_type=schemaType(doc,items);const itemFields=schemaFields(doc,items,depth+1);if(itemFields.length)field.item_fields=itemFields;}else{const nested=schemaFields(doc,definition,depth+1);if(nested.length)field.fields=nested;}}return field;});}
function parameterSummary(doc:JsonObject,value:unknown){const parameter=resolveRef(doc,value);const schema=parameter.schema;return {name:typeof parameter.name==='string'?parameter.name:'unknown',in:typeof parameter.in==='string'?parameter.in:'unknown',required:parameter.required===true,type:schemaType(doc,schema),fields:schemaFields(doc,schema)};}
function mediaSchema(doc:JsonObject,contentValue:unknown){const content=object(contentValue);const preferred=content['application/json']||content['text/json']||content['application/*+json'];if(preferred)return object(preferred).schema;const first=Object.values(content)[0];return object(first).schema;}
function responseSummary(doc:JsonObject,operation:JsonObject){const responses=object(operation.responses);const raw=responses['200']||responses['201']||responses['202']||responses.default;if(!raw)return null;const response=resolveRef(doc,raw);const schema=mediaSchema(doc,response.content);if(!schema)return null;const resolved=resolveRef(doc,schema);const type=schemaType(doc,schema);const summary:Record<string,unknown>={type,fields:schemaFields(doc,schema)};if(type.includes('array')){summary.item_type=schemaType(doc,resolved.items);summary.item_fields=schemaFields(doc,resolved.items);}return summary;}
async function truckDownToken(){const names=await secrets.listSecretNames();if(!names.includes('TRUCKDOWN_API_KEY'))return null;return secrets.readSecret('TRUCKDOWN_API_KEY');}
async function openApiDoc(token:string){if(openApiCache&&openApiCache.expires>Date.now())return openApiCache.doc;const response=await fetch(TRUCKDOWN_OPENAPI_URL,{method:'GET',headers:{Accept:'application/json',Authorization:`Bearer ${token}`},redirect:'manual'});if(!response.ok)throw new Error(`TRUCKDOWN_OPENAPI_${response.status}`);const doc=object(await response.json());openApiCache={expires:Date.now()+10*60*1000,doc};return doc;}
function searchContract(doc:JsonObject){const pathObject=object(object(doc.paths)['/client/search']);const operation=object(pathObject.post);if(!Object.keys(operation).length)return null;const requestSchema=mediaSchema(doc,object(operation.requestBody).content);return {path:'/client/search',method:'POST',operation,requestSchema};}
function parseCoordinates(location:string){const match=location.match(/^\s*(-?\d{1,3}(?:\.\d+)?)\s*,\s*(-?\d{1,3}(?:\.\d+)?)\s*$/);if(!match)return null;const lat=Number(match[1]);const lon=Number(match[2]);if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat<-90||lat>90||lon<-180||lon>180)return null;return {lat,lon};}
function buildSearchBody(doc:JsonObject,requestSchema:unknown,lat:number,lon:number,canonicalService:string){const root=resolveRef(doc,requestSchema);const properties=object(root.properties);const coordinateDefinition=properties.coordinate;if(!coordinateDefinition)return null;const coordinateSchema=resolveRef(doc,coordinateDefinition);const coordinateProperties=object(coordinateSchema.properties);let latKey='';let lonKey='';for(const key of Object.keys(coordinateProperties)){const n=norm(key);if(!latKey&&(n==='lat'||n==='latitude'||n.endsWith('latitude')))latKey=key;if(!lonKey&&(n==='lng'||n==='lon'||n==='longitude'||n.endsWith('longitude')))lonKey=key;}if(!latKey||!lonKey)return null;const body:Record<string,unknown>={coordinate:{[latKey]:lat,[lonKey]:lon}};if('page' in properties)body.page=1;let serviceFilterApplied=false;const serviceDefinition=properties.service;if(serviceDefinition){const resolved=resolveRef(doc,serviceDefinition);const values=Array.isArray(resolved.enum)?resolved.enum.filter(v=>typeof v==='string') as string[]:[];if(values.length){const keywords=serviceKeywords[canonicalService]||[];const match=values.find(value=>keywords.some(keyword=>norm(value).includes(norm(keyword))));if(match){body.service=match;serviceFilterApplied=true;}}}return {body,serviceFilterApplied,coordinate_fields:{latitude:latKey,longitude:lonKey}};}
function providerArrayScore(items:JsonObject[]){if(!items.length)return 0;return items.slice(0,5).reduce((sum,item)=>{const keys=new Set(Object.keys(item).map(norm));let score=0;if([...keys].some(k=>['id','locationid','vendorid','providerid'].includes(k)))score+=2;if([...keys].some(k=>['name','locationname','vendorname','companyname','businessname'].includes(k)))score+=3;if([...keys].some(k=>k.includes('address')))score+=2;if([...keys].some(k=>k.includes('distance')))score+=2;if([...keys].some(k=>k.includes('phone')))score+=1;if([...keys].some(k=>k.includes('service')))score+=1;return sum+score;},0)/Math.min(items.length,5);}
function bestObjectArray(value:unknown,depth=0):{items:JsonObject[];score:number}{if(depth>4)return {items:[],score:0};let best={items:[] as JsonObject[],score:0};if(Array.isArray(value)){const items=value.filter(v=>v&&typeof v==='object'&&!Array.isArray(v)).map(v=>object(v));const score=providerArrayScore(items);if(score>best.score)best={items,score};for(const item of items.slice(0,3)){const nested=bestObjectArray(item,depth+1);if(nested.score>best.score)best=nested;}return best;}const record=object(value);for(const child of Object.values(record)){const nested=bestObjectArray(child,depth+1);if(nested.score>best.score)best=nested;}return best;}
function findValue(value:unknown,names:string[],depth=0):unknown{if(depth>2)return undefined;const record=object(value);const wanted=new Set(names.map(norm));for(const [key,candidate] of Object.entries(record))if(wanted.has(norm(key)))return candidate;for(const candidate of Object.values(record))if(candidate&&typeof candidate==='object'&&!Array.isArray(candidate)){const found=findValue(candidate,names,depth+1);if(found!==undefined)return found;}return undefined;}
function asString(value:unknown){if(typeof value==='string'&&value.trim())return value.trim();if(typeof value==='number'&&Number.isFinite(value))return String(value);return null;}
function asNumber(value:unknown){if(typeof value==='number'&&Number.isFinite(value))return value;if(typeof value==='string'&&value.trim()&&Number.isFinite(Number(value)))return Number(value);return null;}
function addressString(item:JsonObject){const direct=findValue(item,['address','fullAddress','formattedAddress']);if(typeof direct==='string'&&direct.trim())return direct.trim();const addressObj=object(direct);const source=Object.keys(addressObj).length?addressObj:item;const parts=[findValue(source,['address1','addressLine1','street','street1','line1']),findValue(source,['address2','addressLine2','line2']),findValue(source,['city']),findValue(source,['state','province','region']),findValue(source,['postalCode','zip','zipCode'])].map(asString).filter(Boolean);return parts.length?parts.join(', '):null;}
function serviceList(item:JsonObject){const raw=findValue(item,['services','serviceNames','serviceList','serviceCategories']);if(typeof raw==='string')return raw.split(',').map(v=>v.trim()).filter(Boolean).slice(0,10);if(Array.isArray(raw))return raw.map(value=>typeof value==='string'?value:asString(findValue(object(value),['name','title','description']))).filter((v):v is string=>Boolean(v)).slice(0,10);return [] as string[];}
function normalizeCandidates(payload:unknown){const selected=bestObjectArray(payload).items.slice(0,12);const observedAt=new Date().toISOString();return selected.map((item,index):Candidate=>({candidate_id:`candidate_${index+1}`,source:'TRUCKDOWN',external_provider_ref:asString(findValue(item,['locationId','id','vendorId','providerId'])),name:asString(findValue(item,['locationName','vendorName','companyName','businessName','name']))||'TruckDown service provider',address:addressString(item),distance_miles:asNumber(findValue(item,['distanceMiles','distance','miles'])),phone:asString(findValue(item,['phoneNumber','primaryPhone','phone'])),rating:asNumber(findValue(item,['averageRating','rating'])),services:serviceList(item),observed_at:observedAt}));}
function applyLocalServiceFilter(candidates:Candidate[],canonicalService:string){const keywords=serviceKeywords[canonicalService]||[];if(!keywords.length)return {candidates,applied:false};const matches=candidates.filter(candidate=>candidate.services.some(service=>keywords.some(keyword=>norm(service).includes(norm(keyword)))));return matches.length?{candidates:matches,applied:true}:{candidates,applied:false};}
async function providerStatus(){const token=await truckDownToken();if(!token)return {provider:'truckdown',configured:false,authenticated:false,search_ready:false,reason:'TRUCKDOWN_API_KEY_NOT_CONFIGURED'};try{const response=await fetch(TRUCKDOWN_CONTEXT_URL,{method:'GET',headers:{Accept:'application/json',Authorization:`Bearer ${token}`},redirect:'manual'});if(!response.ok)return {provider:'truckdown',configured:true,authenticated:false,search_ready:false,reason:'TRUCKDOWN_AUTH_FAILED',upstream_status:response.status};const context=await response.json();return {provider:'truckdown',configured:true,authenticated:true,search_ready:true,reason:'TRUCKDOWN_READ_ONLY_SEARCH_WIRED',account_type:safeAccountType(context)};}catch(error){console.warn('TruckDown context probe failed',error instanceof Error?error.message:'unknown');return {provider:'truckdown',configured:true,authenticated:false,search_ready:false,reason:'TRUCKDOWN_CONTEXT_UNAVAILABLE'};}}
async function schemaStatus(){const token=await truckDownToken();if(!token)return {available:false,reason:'TRUCKDOWN_API_KEY_NOT_CONFIGURED',search_operation:null,operations:[]};try{const doc=await openApiDoc(token);const paths=object(doc.paths);const operations:Array<Record<string,unknown>>=[];for(const [path,pathValue] of Object.entries(paths)){const pathObject=object(pathValue);for(const method of ['get','post','put','patch','delete']){const operation=object(pathObject[method]);if(!Object.keys(operation).length)continue;const tags=Array.isArray(operation.tags)?operation.tags.filter(v=>typeof v==='string').join(' '):'';const hay=`${path} ${operation.operationId||''} ${operation.summary||''} ${tags}`.toLowerCase();if(!/(search|location|service)/.test(hay))continue;const parameters=[...(Array.isArray(pathObject.parameters)?pathObject.parameters:[]),...(Array.isArray(operation.parameters)?operation.parameters:[])].slice(0,40).map(v=>parameterSummary(doc,v));const requestSchema=mediaSchema(doc,object(operation.requestBody).content);operations.push({path,method:method.toUpperCase(),operation_id:typeof operation.operationId==='string'?operation.operationId:null,summary:typeof operation.summary==='string'?operation.summary:null,parameters,request_fields:schemaFields(doc,requestSchema),response:responseSummary(doc,operation)});if(operations.length>=40)break;}if(operations.length>=40)break;}const exact=operations.find(op=>op.path==='/client/search'&&op.method==='POST')||operations.find(op=>`${op.operation_id||''}`==='SearchByGeocode')||null;return {available:true,reason:exact?'TRUCKDOWN_SEARCH_OPERATION_DISCOVERED':'TRUCKDOWN_OPENAPI_DISCOVERED_SEARCH_OPERATION_NOT_SELECTED',openapi_version:typeof doc.openapi==='string'?doc.openapi:'unknown',search_operation:exact,operations};}catch(error){console.warn('TruckDown OpenAPI probe failed',error instanceof Error?error.message:'unknown');return {available:false,reason:'TRUCKDOWN_OPENAPI_FETCH_FAILED',search_operation:null,operations:[]};}}
async function runSearch(location:string,canonicalService:string){const coordinates=parseCoordinates(location);if(!coordinates)return {status:200,data:{contract_version:'rigdesk-roadside-v0.1',outcome:'coordinates_required',reason:'LIVE_PREVIEW_REQUIRES_LATITUDE_LONGITUDE',canonical_service:canonicalService,persists_input:false,creates_service_request:false,dispatches_provider:false,authorizes_repair:false}};const token=await truckDownToken();if(!token)return {status:503,data:{outcome:'provider_unavailable',reason:'TRUCKDOWN_API_KEY_NOT_CONFIGURED'}};try{const doc=await openApiDoc(token);const contract=searchContract(doc);if(!contract)return {status:503,data:{outcome:'provider_unavailable',reason:'TRUCKDOWN_SEARCH_OPERATION_NOT_FOUND'}};const built=buildSearchBody(doc,contract.requestSchema,coordinates.lat,coordinates.lon,canonicalService);if(!built)return {status:503,data:{outcome:'provider_unavailable',reason:'TRUCKDOWN_COORDINATE_SCHEMA_UNSUPPORTED'}};const response=await fetch(TRUCKDOWN_SEARCH_URL,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(built.body),redirect:'manual'});if(!response.ok){console.warn('TruckDown search failed',response.status);return {status:502,data:{outcome:'provider_search_failed',reason:'TRUCKDOWN_SEARCH_UPSTREAM_ERROR',upstream_status:response.status}};}const payload=await response.json();let candidates=normalizeCandidates(payload);const local=applyLocalServiceFilter(candidates,canonicalService);candidates=local.candidates;return {status:200,data:{contract_version:'rigdesk-roadside-v0.1',outcome:'ok',provider:'truckdown',source_operation:'SearchByGeocode',canonical_service:canonicalService,service_filter_applied:built.serviceFilterApplied,local_service_filter_applied:local.applied,candidate_set:{candidate_set_id:`set_${Date.now().toString(36)}`,source:'TRUCKDOWN',observed_at:new Date().toISOString(),candidate_count:candidates.length,candidates},roadside_handoff:null,persists_input:false,creates_service_request:false,dispatches_provider:false,authorizes_repair:false,returns_vehicle_to_service:false}};}catch(error){console.warn('TruckDown search unavailable',error instanceof Error?error.message:'unknown');return {status:502,data:{outcome:'provider_search_failed',reason:'TRUCKDOWN_SEARCH_UNAVAILABLE'}};}}

export const handler=router({
  'GET /api/_healthcheck':[async()=>json({message:'Success'})],
  'GET /api/roadside/provider-status':[async()=>json(await providerStatus())],
  'GET /api/roadside/schema-status':[async()=>json(await schemaStatus())],
  'POST /api/roadside/search':[async({body})=>{const input=(body||{}) as Record<string,unknown>;const location=typeof input.location==='string'?input.location.trim():'';const service=typeof input.service==='string'?input.service:'';if(location.length<2||location.length>180||!allowedServices.has(service))return json({outcome:'invalid_request',reason:'LOCATION_AND_SUPPORTED_SERVICE_REQUIRED'},400);const result=await runSearch(location,service);return json(result.data,result.status);}]
});